name: test

on: 
  push:
    branches:
    - "**"
  pull_request: {}

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.12.x, 1.13.x, 1.14.x, 1.15.x, 1.16.x, 1.17.x]
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: checkout
        uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
            version: v1.45.2

  test:
    name: go test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.12.x, 1.13.x, 1.14.x, 1.15.x, 1.16.x, 1.17.x]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          version: ${{ matrix.go-version }}
      - name: checkout
        uses: actions/checkout@v3
      - name: Run go tests
        env:
          GO111MODULE: on
        run: |
          go test ./... -v
